name: Gitleaks Security Scan

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks-scan:
    # runs-on: dev-bastion
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1 # Setting it to '0' will allow full history, gitleaks inspect historical commits too

    - name: Set up Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Required for organization-owned repos
        GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true # Uploads results.sarif as a workflow artifact
        GITLEAKS_ENABLE_SUMMARY: true # Adds a report summary to the job page
        GITLEAKS_NOTIFY_USER_LIST : '@awatiirf' # Comma-separated list of GitHub usernames to notify on findings
      